services:
  database:
    container_name: ${MYSQL57_CONTAINER_NAME}
    platform: linux/x86_64
    image: mysql:5.7.44
    restart: unless-stopped
    volumes:
      - ./mysql/5.7.44:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_57_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_57_DATABASE}
      MYSQL_USER: ${MYSQL_57_USER}
      MYSQL_PASSWORD: ${MYSQL_57_PASSWORD}
    ports:
      - "${MYSQL_57_PORT}:3306"
    networks:
      - network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  phpmyadmin:
    container_name: ${PHPMYADMIN_CONTAINER_NAME}
    platform: linux/x86_64
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_57_ROOT_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_57_ROOT_PASSWORD}
    networks:
      - network

  php74:
    container_name: ${PHP74_CONTAINER_NAME}
    build:
      context: ./www/php74
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./www/php74:/var/www/html
    ports:
      - "${PHP_74_PORT}:80"
    depends_on:
      database:
        condition: service_healthy
    environment:
      - MYSQL_HOST=database
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=${MYSQL_57_DATABASE}
      - MYSQL_USER=${MYSQL_57_USER}
      - MYSQL_PASSWORD=${MYSQL_57_PASSWORD}
    networks:
      - network

  php82:
    container_name: ${PHP82_CONTAINER_NAME}
    build:
      context: ./www/php82
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./www/php82:/var/www/html
    ports:
      - "${PHP_82_PORT}:80"
    depends_on:
      database:
        condition: service_healthy
    environment:
      - MYSQL_HOST=database
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=${MYSQL_57_DATABASE}
      - MYSQL_USER=${MYSQL_57_USER}
      - MYSQL_PASSWORD=${MYSQL_57_PASSWORD}
    networks:
      - network

  php85:
    container_name: ${PHP85_CONTAINER_NAME}
    build:
      context: ./www/php85
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./www/php85:/var/www/html
    ports:
      - "${PHP_85_PORT}:80"
    depends_on:
      database:
        condition: service_healthy
    environment:
      - MYSQL_HOST=database
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=${MYSQL_57_DATABASE}
      - MYSQL_USER=${MYSQL_57_USER}
      - MYSQL_PASSWORD=${MYSQL_57_PASSWORD}
    networks:
      - network

networks:
  network:
    name: ${NETWORK_NAME}
    driver: bridge

volumes:
  mysql:
    name: ${MYSQL57_CONTAINER_NAME}_data
